### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by moddedmcplayer** [LordAkkarin/Beacon#39] opened 2022-03-19 06:43 UTC
Bacon crashes on startup.

**Reproduction Steps**
Describe the steps to reproduce the behavior:
1. Click on 'Bacon.exe'

**Expected Behavior**
Bacon should start

**Screenshots**
![image](https://user-images.githubusercontent.com/76910334/159110659-b5dc642b-86c8-4c63-a012-8a69dab1a7a9.png)

**Environment (please complete the following information):**
 - OS: Windows
 - Application Version: 2.4.0

**Additional Context**
Error message:
java.lang.NullPointerException: Cannot invoke "javafx.scene.Node.getLayoutBounds()" because "this.textNode" is null
at com.jfoenix.skins.JFXTextFieldSkin.updateTextPos(JFXTextFieldSkin.java:109) ~[Beacon.exe:?]
	at com.jfoenix.skins.JFXTextFieldSkin.layoutChildren(JFXTextFieldSkin.java:93) ~[Beacon.exe:?]
	at javafx.scene.control.Control.layoutChildren(Control.java:601) ~[Beacon.exe:?]
	at javafx.scene.Parent.layout(Parent.java:1204) ~[Beacon.exe:?]
	at javafx.scene.Parent.layout(Parent.java:1211) ~[Beacon.exe:?]
	at javafx.scene.Parent.layout(Parent.java:1211) ~[Beacon.exe:?]
	at javafx.scene.Parent.layout(Parent.java:1211) ~[Beacon.exe:?]
	at javafx.scene.Parent.layout(Parent.java:1211) ~[Beacon.exe:?]
	at javafx.scene.Parent.layout(Parent.java:1211) ~[Beacon.exe:?]
	at javafx.scene.Parent.layout(Parent.java:1211) ~[Beacon.exe:?]
	at javafx.scene.Scene.doLayoutPass(Scene.java:576) ~[Beacon.exe:?]
	at javafx.scene.Scene.preferredSize(Scene.java:1748) ~[Beacon.exe:?]
	at javafx.scene.Scene$2.preferredSize(Scene.java:393) ~[Beacon.exe:?]
	at com.sun.javafx.scene.SceneHelper.preferredSize(SceneHelper.java:66) ~[Beacon.exe:?]
	at javafx.stage.Window$12.invalidated(Window.java:1086) ~[Beacon.exe:?]
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110) ~[Beacon.exe:?]
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145) ~[Beacon.exe:?]
	at javafx.stage.Window.setShowing(Window.java:1174) ~[Beacon.exe:?]
	at javafx.stage.Window.show(Window.java:1189) ~[Beacon.exe:?]
	at javafx.stage.Stage.show(Stage.java:273) ~[Beacon.exe:?]
	at tv.dotstart.beacon.controller.SplashController$initialize$2.invoke(SplashController.kt:81) ~[Beacon.exe:?]
	at tv.dotstart.beacon.controller.SplashController$initialize$2.invoke(SplashController.kt:40) ~[Beacon.exe:?]
	at tv.dotstart.beacon.preload.Preloader$invoke$1$5.run(Preloader.kt:117) ~[Beacon.exe:?]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428) ~[Beacon.exe:?]
	at java.security.AccessController.doPrivileged(AccessController.java:399) ~[?:?]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427) ~[Beacon.exe:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96) ~[Beacon.exe:?]
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[Beacon.exe:?]
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174) ~[Beacon.exe:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by dotStart** [comment] 2022-03-19 09:52
Upgrade to the [latest version](https://github.com/dotStart/Beacon/releases) of Beacon. The 2.x releases are no longer supported.

Duplicate of #1

**Closed as completed by dotStart** 2022-03-19 09:52 UTC
Labels: bug, duplicate, confirmed
