### ISSUE TITLE
The point of offline mode

### ISSUE THREAD

**Issue by huzpsb** [LordAkkarin/Beacon#38] opened 2022-03-05 12:10 UTC
[redacted_see_mail_for_raw]

**Comment by huzpsb** [comment] 2022-03-05 12:11
redacted for a reason.

**Comment by dotStart** [comment] 2022-03-06 17:57
Sorry, but I still don't think that that's worth the amount of time that it would require. Especially when looking at upcoming features to bulletproof gateway detection / supporting gateways that are not UPnP aware.

Realistically Beacon is primarily distributed via GitHub which (as you say) is inaccessible. Additionally, the application is only available in English and German (potentially Japanese in the future). The resulting target audience for this feature is simply ridiculously small and does not warrant the changes and future considerations that would go into this. After all, it's a hobby project. Nothing more, nothing less.

That being said: Anybody is free to fork Beacon in accordance with the Apache License and provide such features themselves (or just host it somewhere where it would actually be accessible). The `--repository` command line parameter can also be used to run against local repositories that have previously been downloaded and/or compiled. For instance: `--disable-cache -r file:///E:/dotStart/Beacon/repositories/indie.dat -r file:///E:/dotStart/Beacon/repositories/steam.dat -r file:///E:/dotStart/Beacon/repositories/tools.dat`. This would disable most critical internet communication within the current versions of Beacon.

**Comment by dotStart** [comment] 2022-03-06 17:57
Duplicate of #37

**Closed as completed by dotStart** 2022-03-06 17:57 UTC
Labels: bug, duplicate, wontfix
